---
- import_tasks: credentials_create.yml
  when: inventory_hostname == groups[openio_keystone_nodes_group][0]

- name: Fetch credentials tokens locally
  synchronize:
    mode: pull
    src: "{{ openio_keystone_credentials_tokens_key_repository }}/"
    dest: "{{ openio_keystone_tmp_keys_dir }}/credential-keys/"
    archive: "yes"
    delete: "yes"
    use_ssh_args: "yes"
  when: inventory_hostname == groups[openio_keystone_nodes_group][0]
  changed_when: false

- name: Copying credentials keys to all keystone hosts
  synchronize:
    mode: push
    src: "{{ openio_keystone_tmp_keys_dir }}/credential-keys/"
    dest: "{{ openio_keystone_credentials_tokens_key_repository }}"
    archive: "yes"
    delete: "yes"
    use_ssh_args: "yes"
  when: inventory_hostname != groups[openio_keystone_nodes_group][0]

- name: Reset credentials keys ownership
  file:
    path: "{{ openio_keystone_credentials_tokens_key_repository }}"
    owner: "{{ openio_keystone_system_user_name }}"
    group: "{{ openio_keystone_system_group_name }}"
    state: directory
    recurse: "yes"
...
