---
- name: Create SQLite directory
  file:
    path: "{{ openio_keystone_database_sqlite_directory }}"
    owner: keystone
    group: keystone
    mode: 0755
    state: directory
  when: openio_keystone_database_engine == 'sqlite'

- name: Create SQLite databases
  file:
    name: "{{ openio_keystone_database_sqlite_directory }}/{{ openio_keystone_database_sqlite_file }}"
    owner: keystone
    group: keystone
    mode: 0644
    state: touch
  changed_when: false
  when: openio_keystone_database_engine == 'sqlite'

- name: Check current state of Keystone DB
  command: "{{ openio_keystone_bindir }}/keystone-manage db_sync --check"
  register: _db_sync_check
  failed_when: "_db_sync_check.rc | int == 1"
  changed_when: false
  run_once: "{{ not openio_keystone_bootstrap_all_nodes }}"

- name: "Perform a Keystone DB sync expand"
  command: "{{ openio_keystone_bindir }}/keystone-manage db_sync --expand"
  run_once: "{{ not openio_keystone_bootstrap_all_nodes }}"
  when:
    - _db_sync_check.rc | int == 2
  ignore_errors: "{{ ansible_check_mode }}"

- name: Perform a Keystone DB sync migrate
  command: "{{ openio_keystone_bindir }}/keystone-manage db_sync --migrate"
  run_once: "{{ not openio_keystone_bootstrap_all_nodes }}"
  when:
    - _db_sync_check.rc | int in [2, 3]
  ignore_errors: "{{ ansible_check_mode }}"

- name: Perform a Keystone DB sync contract
  command: "{{ openio_keystone_bindir }}/keystone-manage db_sync --contract"
  run_once: "{{ not openio_keystone_bootstrap_all_nodes }}"
  when:
    - _db_sync_check.rc | int in [2, 3, 4]
  ignore_errors: "{{ ansible_check_mode }}"
...
