---
- name: "Update APT cache"
  apt:
    update_cache: true
  changed_when: false

- name: Install packages
  package:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ keystone_packages }}"
  loop_control:
    loop_var: pkg

- name: Upgrade python-shade
  pip:
    name: shade
    state: present
    version: '1.22.2'
...
