---
- name: Ensuring local directory to hold the os-client-config file
  file:
    path: /etc/openstack
    state: directory
    owner: root
    group: root
  tags: configure

- name: Adding clouds.yaml for os-client-config for further actions
  template:
    src: clouds.yaml.j2
    dest: /etc/openstack/clouds.yaml
    owner: root
    group: root
    mode: 0400
  no_log: "{{ openio_keystone_no_log }}"
  tags: configure

- name: 'Install configuration logrotate files'
  template:
    src: openstack-keystone.conf.j2
    dest: "{{ openio_keystone_logrotate_file }}"
    owner: root
    group: root
    mode: '0644'
  tags: configure

# this task corrects past errors for Bionic
- name: remove legacy wrong file
  file:
    path: /etc/logrotate.d/openstack-keystone
    state: absent
  when: ansible_os_family == 'Debian'
  tags: configure
...
